### ISSUE TITLE
Getting error while starting this App

### ISSUE THREAD

**Issue by raisudeen** [abhiaiyer91/meteor-pg-apollo-shopping-cart#6]
<img width="1107" alt="screen shot 2016-05-03 at 7 32 24 am" src="https://cloud.githubusercontent.com/assets/2242085/14972987/1cbffe90-1100-11e6-830b-4cc3fea49279.png">

Im new to Meteor. Kindly check it and let me know the fix. Thanks for your contribution to ApolloStack. Expecting more such example Apps from you.

-Raisudeen.

**Comment by abhiaiyer91** [comment]
Sorry was dumb and had an untracked file.
